# Generated by Django 2.1.7 on 2019-07-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='text',
            new_name='sentence',
        ),
        migrations.AddField(
            model_name='sentence',
            name='sub_cat',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sentence',
            name='super_cat',
            field=models.CharField(default='', max_length=200),
        ),
    ]
